# en-zh-demo.yaml

## where the samples will be written
save_data: data/demo
## where the vocab will be written
src_vocab: data/vocab/example.vocab.src
tgt_vocab: data/vocab/example.vocab.tgt
# prevent overwriting existing files in the folder
overwrite: False

#corpus opts:
data:
    corpus_1:
        path_src: data/train_src.txt
        path_tgt: data/train_tgt.txt
    valid:
        path_src: data/valid_src.txt
        path_tgt: data/valid_tgt.txt

# Fix the line below

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: data/demo/model
save_checkpoint_steps: 1000

seed: 3435

train_steps: 30000
valid_steps: 5000
warmup_steps: 4000
report_every: 100

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 5.0

batch_size: 1024
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'
