# wenyan.yaml

## Where the samples will be written
save_data: data/demo
## Where the vocab(s) will be written
##src_vocab: data/wenyan.vocab.src
src_vocab: data/vocab/en.vocab.src
tgt_vocab: data/vocab/zh.vocab.tgt
src_vocab_size: 500000
tgt_vocab_size: 500000
overwrite: True





# Batching
queue_size: 100
bucket_size: 2048
world_size: 1
gpu_ranks: [0]

batch_size: 32
valid_batch_size: 16

# Corpus opts:
data:
    corpus_1:
        path_src: data/train-src.txt
        path_tgt: data/train-tgt.txt
    valid:
        path_src: data/valid-src.txt
        path_tgt: data/valid-tgt.txt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]
queue_size: 100
bucket_size: 2048

# Train batch
batch_size: 32
# Validation batch
valid_batch_size: 16

# Where to save the checkpoints
save_model: opennmt/model
save_checkpoint_steps: 10000
train_steps: 1000000
valid_steps: 5000